version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: f1-dev
    volumes:
      - .:/workspace
    ports:
      - "8888:8888"  # Optional, for Jupyter or testing
    depends_on:
      - F1Data
    command: sleep infinity

  F1Data:
    image: postgres:16
    container_name: f1data_postgres
    environment:
      POSTGRES_USER: f1user
      POSTGRES_PASSWORD: f1pass
      POSTGRES_DB: f1db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "f1user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
